name: AfterPullRequest

on:
  check_run:
    types: [completed]
  # status:
  #   types: [success]

jobs:
  check_suite:
    runs-on: ubuntu-latest

    steps:
      - name: AfterCI
        run: |
          echo "START CI"
