# .github/workflows/after-pullrequest.yml
name: AfterPullRequest
on:
  workflow_run:
    workflows: ["Workflow", "PullRequest"]
    types:
      - completed

jobs:
  check_all_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Check workflow statuses
        run: |
         echo "START" 
