name: AfterPullRequest

on:
  check_run:
    types: [completed]

jobs:
  after-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: AfterPullRequest
        run: |
          echo "START"


