name: AfterPullRequest
on:
  check_run:
    types: [completed]
    branches:
      - 'feature/*'
  status:
    types: [success]
    branches:
      - 'feature/*'

jobs:
  check_all_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Check workflow statuses
        run: |
         echo "START" 
