name: PullRequest

on: [pull_request]

jobs:
  log_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: START PullRequest
        run: |
          echo "START"
