name: Workflow 

on:
  pull_request:
    branches:
      - develop

jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: START Workflow 
        run: |
          echo "START"
